### ISSUE TITLE
TICKER_URL

### ISSUE THREAD

**Issue by quillie** [Egge7/BitcoinPriceLED#7]
Hi,

first of all: thanks for the great content! I love your project.

While installing, however, I'm pretty confident to have found a bug. Please check src/prices.py, line 6:

wrong:
```
TICKER_URL = 'https://www.bitstamp.net/api/v2/ticker/'
```

right:
```
TICKER_URL = 'https://www.bitstamp.net/api/ticker/'
```

Hope this helps,
thx

**Comment by Egge21M** [comment]
Hi,

Thank you for the kind words! Actually this is the first "Issue" i ever received, so thank you for that as well!

Both endpoints return the same value, but Bitstamps documentation recommended the v2/ticker endpoint, so thats what i went along with.

As both endpoints work, why do you consider using the v2 one a problem?

**Comment by quillie** [comment]
Hi,

you are welcome. Keep up the good work!

I see. My node wasn't able to pull any data using the "v2/ticker" link. Could be that my problem was caused by something else.

**Comment by Egge21M** [comment]
The price function needs a currencie pair to work, so finally URL will look like this:
`TICKER_URL = 'https://www.bitstamp.net/api/v2/ticker/BTCUSD'`

However currently I am encountering an issue with the script always going into an error loop on boot until the service restarts itself. I think this happens because the script starts before network is ready...

**Comment by quillie** [comment]
I see. Sorry for being such a pain in the a**, but when I use this in my browser:

```
https://www.bitstamp.net/api/v2/ticker/BTCUSD
```

I get:
```
404 Not Found
```

In contrast, when I use:
```
https://www.bitstamp.net/api/ticker/BTCUSD
```

it gets me a JSON:
```
{"volume": "1491.60916707", "last": "47751.37", "timestamp": "1633342042", "bid": "47737.72", "vwap": "48127.75", "high": "49225.55", "low": "47242.23", "ask": "47749.37", "open": 48231.04}
```

The code in src/prices.py :

```
import json, requests
r = requests.get('https://www.bitstamp.net/api/v2/ticker/BTCUSD').content
dict = json.loads(r)
print(dict)
```

gives me a "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

but

```
import json, requests
r = requests.get('https://www.bitstamp.net/api/ticker/BTCUSD').content
dict = json.loads(r)
print(dict)
```

provides 

```
{'high': '49225.55', 'last': '47599.30', 'timestamp': '1633342787', 'bid': '47589.08', 'vwap': '48126.74', 'volume': '1489.36377708', 'low': '47242.23', 'ask': '47597.46', 'open': '48231.04'}
```

To be fair, my knowledge in CS is pretty limited, so there might be good reasons why the first URL doesn't work. Just trying to find out why.

**Comment by Egge21M** [comment]
Huh, thats so weird! Have a look at this:
![Photo](https://user-images.githubusercontent.com/80262989/135836697-583a4662-6cb8-4c3a-9034-fabcec780cd8.jpg)

I will add error handling for the API and include the V1 as a fallback.
Thanks for bringing this up!

**Comment by quillie** [comment]
That's weird indeed. Hope this will help a few folks. Thanks!
